export const nfIcons: { [key: string]: string } = {
  java: '',
  rust: '',
  vite: '',
  typescript: '',
  javascript: '',
  webpack: '',
  less: '',
  sass: '',
  css: '',
  html: '',
  c: '',
  'c#': '',
  'c++': '',
  react: '',
  firefox: '',
  chrome: '',
  globe: '',
  youtube: '󰗃',
  twitch: '󰕃',
  discord: '󰙯',
  github: '',
};
