name: Build check
on: 
  pull_request:

jobs:
  cargo:
    name: Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: |
          mkdir -p dist
          pnpm less:build
          cargo build
  whiskers:
    name: Whiskers
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Setup Catppuccin Whiskers
       uses: catppuccin/setup-whiskers@v1.0.0
     - name: Check whiskers
       run: whiskers catppuccin.tera --check
